### ISSUE TITLE
OPAT Flow review

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal-opat#12]
After six months of operation, we have reviewed the patient flow for OPAT.

The team feel that there are some alterations that would meet their needs better. These recommendations were discussed with users at a meeting at HTD on 19/8/15.
## Entering the service

There are broadly two cases for patients being referred to the OPAT team: 
1. Inpatients before they start OPAT care
2. Other patients before they start OPAT care

Inpatients will often be on inpatient teams within the system at the time they are referred. 

Those patients will obviously continue to be treated by inpatient teams until they are discharged - and those clinical interactions will be useful information for the OPAT team when the patient starts OPAT treatment.

It might be more useful for the creation of a separate episode and the copying of data to happen at the point that the patient is _accepted_ to OPAT rather than referred.

It should also be possible for patients on the referrals list to be added to, for instance, an ID liaison team - and for the liaison team to enter notes and advice on the same episode.

The material change here is the observation that OPAT care only starts on the date that the patient is accepted onto the service - this is generally the same time that they are moved from OPAT Referrals -> OPAT Current.
## Moving within the service

When patients revert from the follow up list back to being under OPAT care, we should treat this as a new OPAT admission - in fact they should return to the referrals screen to be triaged with the same processes that they would be were this their first referral.
## Leaving the service

When patients leave the service and are admitted to a ward, the system should automatically add the patient to that team if they are not there already. The system should allow users to add patients to inpatient teams - as the Walk In service does at the end of appointment.

@GabPoll @michaeledwardmarks Your thoughts on this would be welcome!

(Also if @GabPoll could verify that I have captured the recommendations accurately that would be great)

**Comment by GabPoll** [comment]
**Entering service** - good synopsis. Agree with OPAT episode starting on acceptance into OPAT, not referral.

**Moving within service** - also agree. Summarises discussion well.

**Leaving the service** - also agree. There will need to be some importing of OPAT episode information into the new inpatient episode, or perhaps a signpost that old OPAT info is available in History.

**Comment by davidmiller** [comment]
@michaeledwardmarks - I think we discussed this in person last week - can't remember what your thoughts were though ?

**Comment by michaeledwardmarks** [comment]
My only question is:
You are on follow-up. 
I see you in OPAT clinic.
I decide you need to go back on IV.
- We AGREE this will now be a new episode

But
Do we move to referral and then back to current (although we already know we are putting them back on IV)
OR
Move them straight to current

**Comment by michaeledwardmarks** [comment]
Flow Outcomes.
- Add to OPAT Referral
- [x] Capture Referring Team #16 (Dropdown as per NORS) and Consultant (Free-Text)
- Referral > Current
- [x] QC Check Referring Team #16 and Allergies #13 
- On Current AND Finishing IV
- [x] Complete Primary Infective Diagnosis
- [x] Complete NORS Outcomes #25 
- [x] Set-OPAT Review date (as already)

From OPAT-Current can either move to
- OPAT-Follow-Up

OR
- OPAT-Review
  No extra steps beyond the above in either case
- On OPAT-Follow-up can either
  - End OPAT (no extra steps, because NORS and PID collected at end of PID and OPAT Review date already set)

OR
- Return to IV
  - [x] Make a new episode
  - [x] Re-capture route of referral #16 
  - [x] Copy over relevant information from previous episode
  - [x] Record some kind of marker that some of this stuff is imported from an old episode (I guess the date of OPAT Referral will work which we already collect)

**Comment by davidmiller** [comment]
Deployed to david-staging

**Comment by michaeledwardmarks** [comment]
Overall this is looking good.

**NORS Outcome Data Collection Timing**
1) On OPAT-Current when completing IV you currently only get asked the NORS stuff if you select Completed OPAT not if moving to OPAT-Follow-Up.
I believe the flow is that we capture the NORS stuff on everyone at the end of IV regardless of whether they finished all "OPAT Care" or just moved to "OPAT-Follow-Up"

2) Therefore we don't ask NORS stuff when someone finishes on OPAT-Follow-up because we collected it when they finished IV therapy.

**Separate Issue**
- When you click the Accept onto OPAT button on Referrals, it then loads the OPAT next stage (completed-IV/completed OPAT) modal. (BUG)
- And then triggers a saved by someone else error message"
  ![screen shot 2015-10-09 at 19 27 06](https://cloud.githubusercontent.com/assets/4578105/10402203/d4c1ce16-6ebb-11e5-8ee0-1c51221bfc96.png)

**Comment by davidmiller** [comment]
@michaeledwardmarks I've updated the flow to capture NORS regardless of the patient's destination post OPAT current, and stopped the discharge modal from getting confused while we're finishing saving.

**Comment by michaeledwardmarks** [comment]
I've put this in slack but put here it here also.

I don't think we had initially planned to collect NORS at the end of OPAT-Follow-Up.
My understanding was we collect it
- End of OPAT-Current (end of IV Therapy) - Correct
- At an unspecified future date via OPAT Review - Correct.

However:
- [x] Option 1 (Preference):
- Leave it as it is (extra data better and lets us compare NORS at end of IV to end of overall episode)
- If this is being done then we need to change the way the "Outcome stage" is recorded in OPAT-Outcomes to allow differentiation of NORS at end of  OPAT-Current and end of OPAT-Follow-Up.
  This wording change could be in line with #33
- [ ] Option 2 (less good I think)
- Drop NORS from OPAT-Follow-up
- Would still need to ask the non-NORS questions at the end of OPAT-Follow-up (OPAT-Review date, Died, Readmitted)

**Comment by davidmiller** [comment]
Sure, wording changed.
